# Generated by Django 4.2 on 2023-05-03 13:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True, verbose_name='титле')),
                ('order', models.IntegerField(default=0, verbose_name='ордер')),
            ],
            options={
                'verbose_name': 'категория',
                'verbose_name_plural': 'категории',
                'db_table': 'category',
                'ordering': ('order',),
            },
        ),
        migrations.CreateModel(
            name='GroupService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('my_order', models.IntegerField(default=0)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Service.category')),
            ],
            options={
                'db_table': 'group_service',
                'ordering': ('my_order',),
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='наме')),
                ('url', models.URLField(verbose_name='урл')),
                ('icon', models.FileField(null=True, upload_to='icons', verbose_name='икона')),
                ('description', models.CharField(default='Онлайн', max_length=100, verbose_name='описание')),
                ('my_order', models.IntegerField(default=0)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='Service.groupservice')),
            ],
            options={
                'db_table': 'service',
                'ordering': ('my_order',),
            },
        ),
    ]
