# Generated by Django 4.2 on 2023-06-01 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        ('Service', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='role',
            field=models.ManyToManyField(blank=True, max_length=150, to='users.role', verbose_name='роль'),
        ),
    ]
